### PR TITLE
Development

### PR DESCRIPTION
**Pull request by rkemmy**
**What this PR does:**
This PR creates user stories.

Task description:
Create a user sign up template.
Create a user login template.
Create a landing page.

Manual testing:
$ git clone 
$ cd fast_food_fast https://github.com/rkemmy/fast-food.git
$ git checkout development
Access the UI folder and open the html folder. Open the index.html  file in the browser.

**Screenshots**

**Sign Up page**
image

**Login Page**
image

**Landing page**
image

### CODE REVIEW

**Comment by danielotieno** [comment]
Awesome!

**Comment by ThaDeveloper** [comment]
Great layout.

**Comment by Darius-Ndubi** [comment]
Great choice of colors

**Comment by rkemmy** [comment]
Thanks guys even with bootstrap I usually struggle with front-end so I appreciate the positive feedback

**Comment by EmmanuelBeja** [comment]
looks great

**Comment by DennisMufasa** [comment]
impressive idea for the landing page

**Pull request closed without merging**
